/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bet.horserisingsun.horseracing.view;

import bet.horserisingsun.horseracing.Main;
import bet.horserisingsun.horseracing.MainFrame;
import bet.horserisingsun.horseracing.controller.HorseController;
import bet.horserisingsun.horseracing.controller.PlayerController;
import bet.horserisingsun.horseracing.model.BetEntity;
import bet.horserisingsun.horseracing.model.HorseEntity;
import bet.horserisingsun.horseracing.model.PlayerEntity;
import bet.horserisingsun.horseracing.model.RaceEntity;
import java.util.ArrayList;
import javax.swing.JComboBox;

public class HorseView extends javax.swing.JFrame {

    /**
     * Creates new form HorseView
     */
    HorseController horseController = new HorseController();
    PlayerController playerController = new PlayerController();
    public static ArrayList<HorseEntity> horses = new ArrayList<>();
    public static ArrayList<PlayerEntity> players = MainFrame.players;
    public static ArrayList<HorseEntity> selectedHorses = new ArrayList<>();

    //public static ArrayList<BetEntity> bets = new ArrayList<>();
    public static ArrayList<RaceEntity> races = new ArrayList<>();
    public static int raceCounter = 0;

    public HorseView() {

        initComponents();

        try {
            horses = Main.gHorses;
            //players = playerController.getPlayers();
            String[] horsesName = new String[4];
            String[] playersName = new String[4];
            int count = 0;
            int count2 = 0;
            while (count <= 3) {
                horsesName[count] = horses.get(count).getName();

                count++;
            }
            while (count2 < players.size()) {
                playersName[count2] = players.get(count2).getName();
                count2++;
            }
            jListHorse.setListData(horsesName);
            for (String name : horsesName) {
                
                if (playersName[0]!=null) {
                    jComboBox1.addItem(name);
                }else{
                    jComboBox1.setEnabled(false);
                }
                
                if (playersName[0]!=null) {
                    jComboBox2.addItem(name);
                }else{
                    jComboBox2.setEnabled(false);
                }
                if (playersName[0]!=null) {
                    jComboBox3.addItem(name);
                }else{
                    jComboBox3.setEnabled(false);
                }
                if (playersName[0]!=null) {
                    jComboBox4.addItem(name);
                }else{
                    jComboBox4.setEnabled(false);
                }
                
                
            }

            
            jLabelJugador1.setText(playersName[0]);
            jLabelJugador2.setText(playersName[1]);
            jLabelJugador3.setText(playersName[2]);
            jLabelJugador4.setText(playersName[3]);

        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListHorse = new javax.swing.JList<>();
        jLabelJugador1 = new javax.swing.JLabel();
        jLabelJugador2 = new javax.swing.JLabel();
        jLabelJugador3 = new javax.swing.JLabel();
        jLabelJugador4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextFieldAmount1 = new javax.swing.JTextField();
        jTextFieldAmount2 = new javax.swing.JTextField();
        jTextFieldAmount3 = new javax.swing.JTextField();
        jTextFieldAmount4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonPlay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jListHorse);

        jLabelJugador1.setText("jugador 1");

        jLabelJugador2.setText("jugador 2");

        jLabelJugador3.setText("jugador 3");

        jLabelJugador4.setText("jugador 4");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextFieldAmount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAmount1ActionPerformed(evt);
            }
        });

        jTextFieldAmount2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAmount2ActionPerformed(evt);
            }
        });

        jTextFieldAmount4.setToolTipText("");

        jLabel1.setText("cantidad");

        jLabel2.setText("cantidad");

        jLabel3.setText("cantidad");

        jLabel4.setText("cantidad");

        jButtonPlay.setText("A jugar!");
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelJugador1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelJugador2)
                            .addComponent(jLabelJugador3)
                            .addComponent(jLabelJugador4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldAmount3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldAmount4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jTextFieldAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButtonPlay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelJugador1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelJugador2)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelJugador3)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAmount3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelJugador4)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAmount4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(46, 46, 46)
                .addComponent(jButtonPlay)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private HorseEntity getSelectedHorse(JComboBox<String> jc) {

        HorseEntity selectedHorse = new HorseEntity();
        selectedHorse.setName(jc.getSelectedItem().toString());

        if (selectedHorse.getName().equals("Mostufa")) {
            selectedHorse.setId(1);
        }
        if (selectedHorse.getName().equals("Omicron")) {
            selectedHorse.setId(2);
        }
        if (selectedHorse.getName().equals("Paracron")) {
            selectedHorse.setId(3);
        }
        if (selectedHorse.getName().equals("Trueno")) {
            selectedHorse.setId(4);
        }
        return selectedHorse;
    }

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextFieldAmount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAmount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAmount1ActionPerformed

    private void jTextFieldAmount2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAmount2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAmount2ActionPerformed

    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed
        ArrayList<BetEntity> bets = new ArrayList<>();
        

        for (int i = 0; i < players.size(); i++) {
            BetEntity bet = new BetEntity();
            bet.setPlayer(players.get(i));
            if (i == 0) {
                bet.setHorse(getSelectedHorse(jComboBox1));
                bet.setBetAmount(Integer.parseInt(jTextFieldAmount1.getText()));
            }
            if (i == 1) {
                bet.setHorse(getSelectedHorse(jComboBox2));
                bet.setBetAmount(Integer.parseInt(jTextFieldAmount2.getText()));
            }
            if (i == 2) {
                bet.setHorse(getSelectedHorse(jComboBox3));
                bet.setBetAmount(Integer.parseInt(jTextFieldAmount3.getText()));
            }
            if (i == 3) {
                bet.setHorse(getSelectedHorse(jComboBox4));
                bet.setBetAmount(Integer.parseInt(jTextFieldAmount4.getText()));
            }
            bets.add(bet);

        }
        System.out.println("Betamount");
        System.out.println(bets.get(0).getBetAmount());

        RaceEntity race = new RaceEntity();
        race.setId(raceCounter + 1);
        race.setHorses(horses);
        race.setBets(bets);
        int totalRaceAmount = 0;
        for (BetEntity b : bets) {
            totalRaceAmount = totalRaceAmount + b.getBetAmount();
        }
        race.setTotalBetAmount(totalRaceAmount);
        races.add(race);
        WinnerView w = new WinnerView();
        
        w.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonPlayActionPerformed

    public void fillHorses(ArrayList<HorseEntity> horses) throws Exception {
        horses = horseController.getHorses();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HorseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HorseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HorseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HorseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new HorseView().setVisible(true);

            }
        }
        );
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelJugador1;
    private javax.swing.JLabel jLabelJugador2;
    private javax.swing.JLabel jLabelJugador3;
    private javax.swing.JLabel jLabelJugador4;
    private javax.swing.JList<String> jListHorse;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAmount1;
    private javax.swing.JTextField jTextFieldAmount2;
    private javax.swing.JTextField jTextFieldAmount3;
    private javax.swing.JTextField jTextFieldAmount4;
    // End of variables declaration//GEN-END:variables
}
